### ISSUE TITLE
0 Downtime

### ISSUE THREAD

**Issue by Immortalin** [jirutka/apk-autoupdate#5]
Hey there, thanks for building this! I run my Ubuntu distros using their livepatch service so critical stuff gets patched live on-the-fly. Is there a way to do this on Alpine too without downtime?

**Comment by jirutka** [comment]
You mean kernel live patching, don't you? Unfortunately there's no such support in Alpine and apk-autoupdate is not designed for updating kernel.

**Comment by FranklinYu** [comment]
> apk-autoupdate is not designed for updating kernel.

What if there is an update to the kernel? Would it be skipped, or would it be installed but no reboot?

**Comment by cdstg** [comment]
Yes some sort of reboot required would be good eg if kernel updated

**Comment by Roy-Orbison** [comment]
I want to update & restart anything that needs it, inc. the kernel. I ended up with these so that updates with a reboot still produce normal output for logging, cron mail, etc. Reboots are scheduled for 1 minute after the end of updates, but can be adjusted with an integer arg in seconds to `reboot-after`.

A script `/usr/local/sbin/reboot-after`:
```sh
#!/bin/sh
sleep "${1:-60}"
exec reboot
```
And in `/etc/apk/autoupdate.conf`: 
```sh
packages_blacklist=
services_whitelist=*
services_blacklist=

kernel_upgraded=0
after_upgrade () {
	for pkg in "$@"; do
		case $pkg in
			linux-asahi-[1-9]* | \
			linux-elm-[1-9]* | \
			linux-eswin-[1-9]* | \
			linux-gru-[1-9]* | \
			linux-jh7100-[1-9]* | \
			linux-lts-[1-9]* | \
			linux-openpax-[1-9]* | \
			linux-p550-[1-9]* | \
			linux-rpi-[1-9]* | \
			linux-sophgo-[1-9]* | \
			linux-spacemit-[1-9]* | \
			linux-stable-[1-9]* | \
			linux-starfive-[1-9]* | \
			linux-virt-[1-9]* )
				einfo 'Scheduling reboot due to kernel upgrade'
				kernel_upgraded=1
				;;
		esac
	done
}
finalize () {
	print_report
	if [ $kernel_upgraded -gt 0 ]; then
		nohup reboot-after >/dev/null 2>&1 &
	fi
}
```
